# zsh with psql client and Yandex certs
FROM ohmyzsh/zsh:latest
WORKDIR /admin
RUN install_packages postgresql-client wget
RUN mkdir -p ~/.postgresql && \
    wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" \
    --output-document ~/.postgresql/root.crt && \
    chmod 0600 ~/.postgresql/root.crt
